### ISSUE TITLE
Merge the Template

### ISSUE THREAD

**Issue by Edison19991109** [YuZJLab/DNA-Seq-Tmpl#1]
Shall we merge the release branch in to the master branch?
Or maybe, we create a branch for review and test?
Best,
Edison

**Comment by YuZJLab** [comment]
Already merged in 466866f78b41fc3bb04c5cda04460352230a4938 with parent e61db1b7f3ce6f5e546d6d13aa899cbc32a89972 and 0f0e5f2f1fd64697294c9c356cde7c393d1f20c0.

**Comment by Edison19991109** [comment]
So we can't set the master as default?
Best,
Edison

**Comment by YuZJLab** [comment]
Will be done later.
